### ISSUE TITLE
「问题」是否收费？

### ISSUE THREAD

**Issue by iRubbish** [geekdada/bob-plugin-deepl-translate#1]
## 大大你好
首先感谢你的无私奉献，也让我知道有一个比谷歌翻译还好用的翻译软件。不过我这官网上看了一下，它这个软件的API好像是收费的，特向大大确认一下是否收费？
如果不是收费的话，不知大大能否分享一下如何获取的一个步骤教程，感谢🙏

**Comment by geekdada** [comment]
我自己开发了一个转发服务，相对便宜地使用 DeepL 接口，你可以到 https://sub-deepl.royli.dev/ 了解。
