### ISSUE TITLE
接口响应错误 Authorization failed. Please supply a valid token.

### ISSUE THREAD

**Issue by callzhang** [geekdada/bob-plugin-deepl-translate#10]
我在官网开通了free的服务，拿到了token但是无效。请问一定要pro版的才行吗？

**Comment by geekdada** [comment]
是的

**Comment by callzhang** [comment]
可以支持一下free的token吗？目前free的足够大部分个人使用了吧。谢谢！

**Comment by geekdada** [comment]
不好意思，我没意识到有免费版了，我会尽快支持。

**Comment by flappyink** [comment]
官方免费版本只是把API域名修改为了：https://api-free.deepl.com
api.js里面的域名修改一下就能使用了

**Comment by liuxieric123** [comment]
对下载的插件更改后缀名，从 bob-plugin-deepl-translate.bobplugin 更改为 bob-plugin-deepl-translate.zip，解压后对文件夹内的 api.js文件中 https://api.deepl.com  更改为 https://api-free.deepl.com。
再对该文件夹内所有文件进行压缩（注意是选中所有文件而不是选中这个文件夹）
把压缩的文件名改为 bob-plugin-deepl-translate.bobplugin

如果想立即使用可以参考这个方法，还是希望开发者尽快支持

**Comment by geekdada** [comment]
https://github.com/geekdada/bob-plugin-deepl-translate/releases/tag/v0.8.0
