### ISSUE TITLE
DeepL 免费 API 无法正常使用

### ISSUE THREAD

**Issue by igocc** [geekdada/bob-plugin-deepl-translate#12]
deepl free 的 api 接口无法正常使用， 提示：接口响应错误 Authorization failed. Please supply a valid token.  请问怎么处理呀？ 谢谢

**Comment by geekdada** [comment]
请检查 Token 是否正确。插件是没问题的。

**Comment by jkhnfk** [comment]
2022-04-02，还是报错，接口响应错误。

**Comment by geekdada** [comment]
我自己也有使用免费的 token，确认插件是没问题的。

请检查是否复制了多于的字符、回车。

**Comment by jkhnfk** [comment]
感谢。我又仔细检查了一下，发现是 deepl 免费的 token，除了 API 之外，还有个什么 CAT 和网页访问，需要在里面更改成 API 的 key 才行。而且填进 bob 之后需要软件重启几次才会有效。

**Comment by YuzhongDing** [comment]
> 感谢。我又仔细检查了一下，发现是 deepl 免费的 token，除了 API 之外，还有个什么 CAT 和网页访问，需要在里面更改成 API 的 key 才行。而且填进 bob 之后需要软件重启几次才会有效。

请问能给个修改CAT和网页访问的链接吗 我找不到在哪里修改

**Comment by geekdada** [comment]
@YuzhongDing 我没太懂你的问题

**Comment by YuzhongDing** [comment]
我也遇到了上面的这个问题，看看之前的comment 有个老哥说要在CAT和网页访问里修改API的key

**Comment by geekdada** [comment]
可是免费的API不可以用于CAT工具，所以我不懂你指的到底是什么，而且与本插件也没有任何关系。

**Comment by 6324tv** [comment]
我也遇到“接口响应错误 Authorization failed. Please supply a valid token.”的问题，可以尝试一下退出软件，重新打开，我的问题就解决了
