### ISSUE TITLE
插件使用报错

### ISSUE THREAD

**Issue by LoneFireBlossom** [geekdada/bob-plugin-deepl-translate#13]
bob最新版，
DeepL免费版，
之前用的好好的，隔了几天没用，今天翻译突然就这样了，不知道为啥，删除插件重新安装也没用，希望开发者能修复一下，真的很需要这个插件😭😭😭

<img width="440" alt="image" src="https://user-images.githubusercontent.com/50087596/141392405-61bbb89d-1880-4d89-8b8a-1ecfe02e7da9.png">

**Comment by geekdada** [comment]
请检查一下你的 Key 是否确实可用

**Comment by LoneFireBlossom** [comment]
的确是可用的，我重制了密钥然后再填进去，还是说错误= =
下面是截图，可能是因为密钥太长了，所以bob里一行显示不下，移动光标可以看到后面的密钥。
重启了一下电脑还是不行
<img width="684" alt="image" src="https://user-images.githubusercontent.com/50087596/141596913-27814d02-2654-4e12-98f9-b63423cfcbb2.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/50087596/141596936-0e86e6f0-5a34-404e-9c60-7c27949ecedb.png">

**Comment by LoneFireBlossom** [comment]
额……找了一下发现，是不是这个的问题？它说9号就失效了，我记不清之前是什么状态了。
但是看这图片上的其它信息也看不出来啥，感觉订阅一切正常才对啊= =

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/50087596/141597618-3cf5e3f0-c958-4414-818e-f39156789f29.png">

我尝试重新点申请API，无论是免费还是pro，都提示我错误：

<img width="863" alt="image" src="https://user-images.githubusercontent.com/50087596/141597653-3366b497-3f10-460f-8213-9b86bf6a45d6.png">
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/50087596/141597663-9a779fef-0174-4663-994d-d22b6e2ce264.png">

是不是我应该找DeepL的客服才对😭

**Comment by geekdada** [comment]
请确认你的用量有没有超过 50 万字符。插件本身是没有问题的。

**Comment by LoneFireBlossom** [comment]
用量的问题我也纳闷……
我明明用过几千到几万个字符额度，之前看过，网站上有记录。这次不知道什么情况，查了一下发现用量是0，明明我设置API还不到一个月呢

<img width="724" alt="image" src="https://user-images.githubusercontent.com/50087596/141600835-92910f52-11fe-4661-ab85-fe40bf762d1a.png">

**Comment by LoneFireBlossom** [comment]
不好意思，确实是我的付款方式的问题……
我谷歌的一个方法说买一个美国虚拟信用卡。我买了之后成功用了十几天就不行了，估计是被发现然后禁止了。
我拜托美国的同学用他的visa卡注册就没问题了。
