### ISSUE TITLE
DeepL Pro Advanced - 接口响应错误 Authorization failed. Please supply a valid token.

### ISSUE THREAD

**Issue by DayuGuo** [geekdada/bob-plugin-deepl-translate#19]
# 问题描述
购买的是 DeepL Pro Advanced，月付，将「账户 - 账户 - 用于CAT工具插件的验证密钥」中的密钥复制到插件中，确认复制无误。

# 报错：
接口响应错误 Authorization failed. Please supply a valid token.

# 实验：
- 尝试重启3次，依旧报错。
- 尝试获取新密钥，依旧报错。
- Bob 已更新到最新，pro 版

谢谢

**Comment by geekdada** [comment]
CAT 的秘钥不可以用于 DeepL API，请购买 API 的秘钥
