### ISSUE TITLE
Download url 404

### ISSUE THREAD

**Issue by DIYgod** [geekdada/bob-plugin-deepl-translate#20]
Hello, today I tried to update the plugin but failed, found that the download url is inaccessible.

https://github.com/geekdada/bob-plugin-deepl-translate/commit/8321dea1ef4758e705f29c8372075d1d77fc55a0

```json
"url": "https://github.com/geekdada/bob-plugin-deepl-translate/releases/download/v0.8.1/bob-plugin-deepl-translate.bobplugin",
```

<img width="925" alt="image" src="https://user-images.githubusercontent.com/8266075/221425136-badc7b13-fb83-4d92-87d7-9f70251f185e.png">

**Comment by geekdada** [comment]
It's fixed now. Thanks a lot!
