### ISSUE TITLE
参数异常: 接口响应错误 Authorization failed. Please supply a valid token.

### ISSUE THREAD

**Issue by Raychanan** [geekdada/bob-plugin-deepl-translate#3]
已经付费，账号 raychanan@gmail.com

![image](https://user-images.githubusercontent.com/53246211/100468283-0f8b7400-310f-11eb-9f8c-7275e5d3eec7.png)

**Comment by Raychanan** [comment]
Solved. Personal input error: input the token for multiple times.

**Comment by geekdada** [comment]
sub deepl 相关的问题请直接使用 Telegram 或 Twitter 和我沟通。
