### ISSUE TITLE
套餐不够使用失败

### ISSUE THREAD

**Issue by d100972** [geekdada/bob-plugin-deepl-translate#5]
当购买的套餐不够时，调用接口失败。
然后我买了新的套餐，但是在老的套餐还没有使用完时，新的套餐(更多的可用字符翻译)无法使用，我需要把老的套餐的字符彻底用完才可以用新的套餐的翻译，这就有了一个 bug，老的套餐还有几十、十几、几个字符没用完，就一直接口调用失败，即使有一个更多字符的新的套餐

**Comment by geekdada** [comment]
是个bug，麻烦使用后台右下角气泡告诉我你的账号。非常抱歉。

**Comment by geekdada** [comment]
已修复该问题。

下次如果遇到 A Translator 的使用问题请直接通过网站右下角气泡进行反馈。
